name: Check isort

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install isort
        run: |
          pip install isort
      - name: run isort
        run: |
          isort --check-only --quiet .
